version: '3.4'

services:
  ffc1:
    image: ffc
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - SDK_KEY=sdk-d153ce08-8c7c-4297-9c51-878e7d55b941
      - STORE_ID=1
      - ENV=development
    ports:
      - 8000:8000
  ffc2:
    image: ffc
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - SDK_KEY=sdk-69da3739-0241-4774-8fe4-ec9340277139
      - STORE_ID=2
      - ENV=production
    ports:
      - 8001:8000
  ffc3:
    image: ffc
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - SDK_KEY=sdk-69da3739-0241-4774-8fe4-ec9340277139
      - STORE_ID=3
      - ENV=production
    ports:
      - 8002:8000